### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by iffanmajid** [Q115/DelayedProgressDialog#1]
Hi I have following issue:

`Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
       at id.mdmedia.newyellowpages.utils.DelayedProgressDialog.showDialogAfterDelay(DelayedProgressDialog.java:90)
       at id.mdmedia.newyellowpages.utils.DelayedProgressDialog.access$100(DelayedProgressDialog.java:34)
       at id.mdmedia.newyellowpages.utils.DelayedProgressDialog$1.run(DelayedProgressDialog.java:83)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

Thanks for the lib anyway

**Comment by Q115** [comment]
Acknowledged. Looks like it fails if you rotate the device before the dialog shows (DELAY_MILLISECOND). Simple fix, I will make the change later tonight. Thanks!

**Comment by Q115** [comment]
Fixed in commit 61e1906
